name: Greetings

on: 
  issues:
    types: [opened]
  pull_request_target:
    types: [opened, reopened]
    
jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: 'Greet the contributor'
      uses: garg3133/welcome-new-contributors@v1.2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi, @${{ github.actor }}. Thank you so much for reporting an issue.'
        pr-message: 'Hi, @${{ github.actor }}. Thank you so much for contributing to this project. Keep making such awesome contributions!'
